// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axtdaqhngdgyvntafjci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dGRhcWhuZ2RneXZudGFmamNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MDY3MzYsImV4cCI6MjA3ODI4MjczNn0.5PXmXi0tlsAMYADT6_dk2N3fbPUrow8CVOps_MxMtt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});